#!/bin/bash
#Напишете скрипт, който приема три задължителни позиционни параметра — директория SRC, директория DST (която не трябва да съдържа файлове)
#и низ ABC. Ако скриптът се изпълнява от root потребителя, то той трябва да намира всички файлове в директорията SRC и нейните под-директории,
#които имат в името си като под-низ ABC, и да ги мести в директорията DST, запазвайки директорийната структура
#(но без да запазва мета-данни като собственик и права).

#Пример:

#в SRC (/src) има файловете: /src/foof.txt, /src/1/bar.txt, /src/1/foo.txt, /src/2/1/foobar.txt, /src/2/3/barf.txt
#DST (/dst) е празна директория
#зададения низ е foo

#Резултат:

#в SRC остават: /src/1/bar.txt, /src/2/3/barf.txt
#в DST се получават: /dst/foof.txt, /dst/1/foo.txt, /dst/2/1/foobar.txt


if [[ ! $(whoami) == "root" ]]; then
   exit 1
fi
SRC=$1
DST=$2
str="ABC"
if [[ -n $(ls $DST) ]]; then
   exit 1
fi
IFS='\n'
for file in $(find "$SRC" -name "*ABC*"); do
    newPath=$(echo $file | sed "s|$SRC|$DST|")
    dirToMake=$(dirname "$newPath")
    if [[ -d $dirToMake ]]; then
       mv "$file" "$dirToMake/$(basename "$file")"
    else
      mkdir -p $dirToMake
      mv "$file" "$dirToMake/$(basename "$file")"
done
