#!/bin/bash
#Напишете скрипт, който приема два позиционни аргумента – име на текстови файл и директория. Директорията не трябва да съдържа обекти, а текстовият файл (US-ASCII) е стенограма и всеки ред е във формат:

#ИМЕ ФАМИЛИЯ (уточнения): Реплика

#където:

#ИМЕ ФАМИЛИЯ присъстват задължително;
#ИМЕ и ФАМИЛИЯ се състоят само от малки/главни латински букви и тирета;
#(уточнения) не е задължително да присъстват;
#двоеточието ':' присъства задължително, с поне един интервал между ИМЕ и ФАМИЛИЯ преди него;
#Репликата не съдържа знаци за нов ред.

#Примерен входен файл:

#John Lennon (The Beatles): Time you enjoy wasting, was not wasted.
#Roger Waters: I'm in competition with myself and I'm losing.
#John Lennon:Reality leaves a lot to the imagination.
#Leonard Cohen:There is a crack in everything, that's how the light gets in.

#Скриптът трябва да:

#създава текстови файл dict.txt в посочената директория, който на всеки ред да съдържа ИМЕ ФАМИЛИЯ;НОМЕР, където ИМЕ ФАМИЛИЯ е уникален участник (без уточненията), а НОМЕР е уникален номер, избран от вас;
#създава файл НОМЕР.txt в посочената директория, съдържащ всички (и само) редовете на дадения участник.


number=0
touch dict.txt
while read -r line; do
    line1=$(echo $line | sed 's/(.*)//')
    name=$(echo $line1 | awk '{print $1}')
    family=$(echo $line1 | awk '{print $2}')
    if ! grep -E "$name $family;.*" dict.txt; then
        number=$((number + 1))
        echo "$name $family;$number" >> dict.txt
    fi
    numberInFile=$(grep "$name $family;.*" dict.txt | awk -F ";" '{print $2}')
    echo "$line1" >> "$2/$numberInFile.txt"
done < "$1"
