#!/bin/bash
#(ACPI wakeup) Linux kernel предоставя виртуален файл /proc/acpi/wakeup за проверка/промяна на настройка за "събуждане" при
#определени събития. Файлът има 4 колони (Device, S-state, Status, Sysfs node), разделени с whitespace; при запис на име на 
#устройство във файла, състоянието disabled/enabled се превключва.

#Дефиниран е формат на конфигурационен файл, описващ желан комплект настройки:

## comment bar
#GLAN disabled
#LID enabled # comment foo

#Напишете скрипт, който при подаден първи параметър — име на конфигурационен файл в горния формат — осигурява исканите настройки за събуждане.
#Ако във файла има ред за устройство, което не съществува, скриптът да извежда предупреждение. Обърнете внимание на обработката на грешки
#и съобщенията към потребителя.


special_file=/proc/acpi/wakeup
if [[ ! -f "$1" ]]; then
   exit 1
sed -e 's/^#.*$//' -e 's/^ *$' $1 | while read -r DEV STATUS; do
   current_line=$(grep -E "^$DEV .*$" $special_file)
   if [[ -n $current_line ]]; then
       if [[ "$STATUS" != "$(echo $current_line | awk '{print $3}' | tr -d '*')" ]]; then
           echo $DEV > $special_file
       fi
    fi
done
