#!/bin/bash
#Министерството на Истината ви поставя спешна задача: да напишете скрипт replace.sh, който замества думи в определени текстове.

#replace.sh приема два типа валидни аргументи:

#Файл: произволен низ, не-започващ с тире — интерпретиран като име на файл
#Замяна: аргумент от вида -R<дума1>=<дума2>

#Редът на аргументите няма значение, а броят им може да е произволен. За всяка замяна, replace.sh трябва да промени всички файлове,
#така че всички срещания на <дума1> да бъдат заменени с <дума2>.

#Забележки:

#думите съдържат само латински букви и цифри; замяната е case sensitive;
#заменят се само пълни думи;
#вече заменена дума не се заменя втори път (решения, не спазващи това, се оценяват с най-много 8 точки);
#не може да разчитате, че фиксиран низ не се среща в никой текст — може да ползвате pwgen(1).

#Пример:

#$ cat propaganda.txt
#Our ally Eastasia is helping us in the war effort against Eurasia.
#$ ./replace.sh -REastasia=Eurasia -REurasia=Eastasia propaganda.txt
#$ cat propaganda.txt
#Our ally Eurasia is helping us in the war effort against Eastasia.

#Бонус: Скриптът да не извършва никаква замяна в редове, които започват със символа #.


i=0
j=0
for arg in "$@"; do
    if [[ "arg" =~ ^-R ]]; then
        toChange[$i]=$(echo "$arg" | tr -d "-R")
        marker=$(pwgen 20 1)
        toChange[$i]="$(toChange[$i]):$marker"
        i=$((i+1))
    else
        files[$j]=$arg
        j=$((j+1))
fi
done
for replace in ${toChange[@]}; do
    wordToReplace=$(echo "$replace" | awk -F "=" '{print $1}')
    markerToPlace=$(echo "$replace" | awk -F ":" '{print $2}')
    for file in ${files[@]}; do
        sed -i "s/\b$wordToReplace\b/$markerToPlace/g" $file
    done
done
for replace in ${toChange[@]}; do
    markerToReplace=$(echo $replace | awk -F ":" '{print $2}')
    wordToPlace=$(echo $replace | awk -F ":" {print $1} | awk -F "=" '{print $2}')
    for file in ${files[@]}; do
        sed -i "s/\b$markerToReplace\b/$wordToPlace/g" $file
    done
done


