#!/bin/bash
if [[ -z "$REGISTRY_FILE" || -z "$REPORTS_DIR" ]]; then
    exit 1
fi
if [[ ! -f "$REGISTRY_FILE" ]]; then
    touch $REGISTRY_FILE
fi
if [[ ! -d "$REPORTS_DIR" ]]; then
    mkdir "$REPORTS_DIR"
fi
currTime=$(date +%Y-%m-%d-%H-%M-%S)
for dir in "$@"; do
    while read file; do
        if ! grep "$file" $REGISTRY_FILE; then
            echo $file >> new_file
        fi
        sha_sum=$(sha256sum $file)
        if 

    done < <(find $dir -type f -exec realpath {} \;)
done
