#!/bin/bash
allFiles=$(find -maxdepth 1 . -type f)
for file in $allFiles; do
    fileLines=$(cat $file | wc -l)
    if [[ $fileLines -lt $1 ]]; then
       mkdir -p ./a
       mv $file ./a
    elif [[ $fileLines -gt $1 && $fileLines -lt $2 ]]; then
       mkdir -p ./b
       mv $file ./b
    else
       mkdir -p ./c
       mv $file ./c
    fi
